parameters:
#    grupo3_taller_unlp_usuario_red.example.class: Grupo3TallerUNLP\UsuarioRedBundle\Example

services:
#    grupo3_taller_unlp_usuario_red.example:
#        class: %grupo3_taller_unlp_usuario_red.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
