<?php

namespace Grupo3TallerUNLP\SitioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SitioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitioRepository extends EntityRepository
{
}
