parameters:
#    grupo3_taller_unlp_oficina.example.class: Grupo3TallerUNLP\OficinaBundle\Example

services:
#    grupo3_taller_unlp_oficina.example:
#        class: %grupo3_taller_unlp_oficina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
