<?php

namespace Grupo3TallerUNLP\ConfiguracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionRepository extends EntityRepository
{
	protected function findByIP($field1, $field2, $field3, $field4){
		$ipAddress = $this->findOneBy(array(
			'field1' => $field1,
			'field2' => $field2,
			'field3' => $field3,
			'field4' => $field4,
		));
		if (!$ipAddress) {
			$ipAddress = new IPAddress();
			$ipAddress->setField1($field1);
			$ipAddress->setField2($field2);
			$ipAddress->setField3($field3);
			$ipAddress->setField4($field4);
			$this->persist($ipAddress);
			$this->flush();
		}
		return $ipAddress;
	}
}