<?php

namespace Grupo3TallerUNLP\InformeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
}
