parameters:
#    grupo3_taller_unlp_informe.example.class: Grupo3TallerUNLP\InformeBundle\Example

services:
#    grupo3_taller_unlp_informe.example:
#        class: %grupo3_taller_unlp_informe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
