configuracion:
    path:     /
    defaults: { _controller: "Grupo3TallerUNLPConfiguracionBundle:Configuracion:index" }

configuracion_edit:
    path:     /{id}/edit
    defaults: { _controller: "Grupo3TallerUNLPConfiguracionBundle:Configuracion:edit" }

configuracion_update:
    path:     /{id}/update
    defaults: { _controller: "Grupo3TallerUNLPConfiguracionBundle:Configuracion:update" }
    requirements: { _method: post|put }
