parameters:
#    grupo3_taller_unlp_user.example.class: Grupo3TallerUNLP\UserBundle\Example

services:
    grupo3_taller_unlp_user.profile.form.type:
        class: Grupo3TallerUNLP\UserBundle\Form\ProfileFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: grupo3tallerunlp_profile }
#    grupo3_taller_unlp_user.example:
#        class: %grupo3_taller_unlp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
