parameters:
#    grupo3_taller_unlp_user.example.class: Grupo3TallerUNLP\UserBundle\Example

services:
#    grupo3_taller_unlp_user.example:
#        class: %grupo3_taller_unlp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
