Grupo3TallerUNLP\PlantillaBundle\Entity\Plantilla:
    type: entity
    table: null
    repositoryClass: Grupo3TallerUNLP\PlantillaBundle\Entity\PlantillaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 50
        descripcion:
            type: string
            length: 70
            nullable: true
    oneToOne:
        informepredefinido:
            targetEntity: Grupo3TallerUNLP\InformePredefinidoBundle\Entity\InformePredefinido
            mappedBy: plantilla
            nullable: true    
    oneToMany:
        valorfiltro:
            orderBy: { 'filtroId': 'ASC' }
            targetEntity: Grupo3TallerUNLP\PlantillaBundle\Entity\ValorFiltro
            mappedBy: plantilla
    manyToOne:
        usuariosistema:
            targetEntity: Grupo3TallerUNLP\UserBundle\Entity\User
            inversedBy: plantilla
            nullable: false
            joinColumn:
                name: usuariosistema
                referencedColumnName: id
                onDelete: "CASCADE"
    lifecycleCallbacks: {  }
    
