<?php

namespace Grupo3TallerUNLP\InformePredefinidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformePredefinidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformePredefinidoRepository extends EntityRepository
{
}
