sitio:
    path:     /
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:index" }

sitio_show:
    path:     /{id}/show
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:show" }
    requirements:
        id: \d+

sitio_show_delete:
    path:     /{id}/delete
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:showDelete" }
    requirements:
        id: \d+

sitio_new:
    path:     /new
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:new" }

sitio_create:
    path:     /create
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:create" }
    methods:  POST

sitio_edit:
    path:     /{id}/edit
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:edit" }
    requirements:
        id: \d+

sitio_update:
    path:     /{id}/update
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:update" }
    methods:  POST|PUT
    requirements:
        id: \d+

sitio_delete:
    path:     /{id}/delete
    defaults: { _controller: "Grupo3TallerUNLPSitioBundle:Sitio:delete" }
    methods:  POST|DELETE
    requirements:
        id: \d+
