parameters:
#    grupo3_taller_unlp_sitio.example.class: Grupo3TallerUNLP\SitioBundle\Example

services:
#    grupo3_taller_unlp_sitio.example:
#        class: %grupo3_taller_unlp_sitio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
