parameters:
#    grupo3_taller_unlp_grupo.example.class: Grupo3TallerUNLP\GrupoBundle\Example

services:
#    grupo3_taller_unlp_grupo.example:
#        class: %grupo3_taller_unlp_grupo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
