parameters:
#    grupo3_taller_unlp_plantilla.example.class: Grupo3TallerUNLP\PlantillaBundle\Example

services:
#    grupo3_taller_unlp_plantilla.example:
#        class: %grupo3_taller_unlp_plantilla.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
